-- Koku schema. Idempotent: safe to run repeatedly.

-- ─── Better Auth core tables ───────────────────────────────────────────────
-- Generated by `npx @better-auth/cli generate`. Do not rename columns —
-- Better Auth queries them verbatim (camelCase, quoted).

CREATE TABLE IF NOT EXISTS "user" (
  "id" text NOT NULL PRIMARY KEY,
  "name" text NOT NULL,
  "email" text NOT NULL UNIQUE,
  "emailVerified" boolean NOT NULL,
  "image" text,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "session" (
  "id" text NOT NULL PRIMARY KEY,
  "expiresAt" timestamptz NOT NULL,
  "token" text NOT NULL UNIQUE,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz NOT NULL,
  "ipAddress" text,
  "userAgent" text,
  "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "account" (
  "id" text NOT NULL PRIMARY KEY,
  "accountId" text NOT NULL,
  "providerId" text NOT NULL,
  "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope" text,
  "password" text,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "verification" (
  "id" text NOT NULL PRIMARY KEY,
  "identifier" text NOT NULL,
  "value" text NOT NULL,
  "expiresAt" timestamptz NOT NULL,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");
CREATE INDEX IF NOT EXISTS "verification_identifier_idx"
  ON "verification" ("identifier");

-- ─── Koku domain tables ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS koku_users (
  id TEXT PRIMARY KEY REFERENCES "user"("id") ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'developer'
    CHECK (role IN ('owner', 'developer', 'project_lead')),
  preferred_language TEXT NOT NULL DEFAULT 'es'
    CHECK (preferred_language IN ('es', 'en')),
  timezone TEXT NOT NULL DEFAULT 'America/Panama',
  after_hours_start TIME DEFAULT '20:00',
  after_hours_end TIME DEFAULT '07:00',
  weekly_mirror_enabled BOOLEAN DEFAULT true,
  baseline_completed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  client_name TEXT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'paused', 'archived')),
  billable BOOLEAN NOT NULL DEFAULT true,
  hourly_rate NUMERIC(10,2),
  created_by TEXT REFERENCES koku_users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS project_members (
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES koku_users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member'
    CHECK (role IN ('lead', 'member')),
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS custom_work_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  scope TEXT NOT NULL CHECK (scope IN ('global', 'project')),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  color TEXT NOT NULL DEFAULT '#6B7280',
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'archived')),
  created_by TEXT REFERENCES koku_users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES koku_users(id),
  project_id UUID NOT NULL REFERENCES projects(id),
  work_type TEXT NOT NULL CHECK (work_type IN (
    'spec', 'build', 'debug', 'polish',
    'devops', 'arch', 'client', 'meeting', 'admin', 'other'
  )),
  custom_work_type_id UUID REFERENCES custom_work_types(id),
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  duration_minutes INTEGER,
  note TEXT,
  feedback TEXT CHECK (feedback IN ('difficult', 'flowed', 'blocked')),
  is_active BOOLEAN DEFAULT false,
  is_baseline BOOLEAN DEFAULT false,
  invoiced BOOLEAN DEFAULT false,
  invoice_id TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS sessions_one_active_per_user
  ON sessions (user_id) WHERE is_active = true;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES koku_users(id),
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS friday_context (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES koku_users(id),
  week_start DATE NOT NULL,
  context TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, week_start)
);

CREATE TABLE IF NOT EXISTS weekly_mirrors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES koku_users(id),
  week_start DATE NOT NULL,
  content TEXT NOT NULL,
  friday_context_used TEXT,
  delivered_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  UNIQUE (user_id, week_start)
);

-- Outbound notification log — used to rate-limit heartbeat + daily + friday pushes.
CREATE TABLE IF NOT EXISTS notification_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES koku_users(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS notification_log_user_tag_idx
  ON notification_log (user_id, tag, sent_at DESC);

-- Indexes on sessions.
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_project_id_idx ON sessions (project_id);
CREATE INDEX IF NOT EXISTS sessions_started_at_idx ON sessions (started_at);
CREATE INDEX IF NOT EXISTS sessions_work_type_idx ON sessions (work_type);
CREATE INDEX IF NOT EXISTS sessions_is_active_idx ON sessions (user_id)
  WHERE is_active = true;

-- ─── FK cascade hardening (idempotent) ────────────────────────────────────
-- Deleting a koku_user or a project should not leave orphan rows.
-- created_by references nullable on delete so history survives.

ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_user_id_fkey;
ALTER TABLE sessions
  ADD CONSTRAINT sessions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES koku_users(id) ON DELETE CASCADE;

ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_project_id_fkey;
ALTER TABLE sessions
  ADD CONSTRAINT sessions_project_id_fkey
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE push_subscriptions DROP CONSTRAINT IF EXISTS push_subscriptions_user_id_fkey;
ALTER TABLE push_subscriptions
  ADD CONSTRAINT push_subscriptions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES koku_users(id) ON DELETE CASCADE;

ALTER TABLE weekly_mirrors DROP CONSTRAINT IF EXISTS weekly_mirrors_user_id_fkey;
ALTER TABLE weekly_mirrors
  ADD CONSTRAINT weekly_mirrors_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES koku_users(id) ON DELETE CASCADE;

ALTER TABLE friday_context DROP CONSTRAINT IF EXISTS friday_context_user_id_fkey;
ALTER TABLE friday_context
  ADD CONSTRAINT friday_context_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES koku_users(id) ON DELETE CASCADE;

ALTER TABLE notification_log DROP CONSTRAINT IF EXISTS notification_log_user_id_fkey;
ALTER TABLE notification_log
  ADD CONSTRAINT notification_log_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES koku_users(id) ON DELETE CASCADE;

ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_created_by_fkey;
ALTER TABLE projects
  ADD CONSTRAINT projects_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES koku_users(id) ON DELETE SET NULL;

ALTER TABLE custom_work_types DROP CONSTRAINT IF EXISTS custom_work_types_created_by_fkey;
ALTER TABLE custom_work_types
  ADD CONSTRAINT custom_work_types_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES koku_users(id) ON DELETE SET NULL;
